name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test - CI (macOS)
      run: |
        xcodebuild clean build test \
        -project EssentialFeed/EssentialFeed.xcodeproj \
        -scheme "CI_macOS" \
        -destination 'platform=macOS' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Build and Test - CI (iOS)
      run: |
        xcodebuild clean build test \
        -project EssentialFeed/EssentialFeed.xcodeproj \
        -scheme "CI_iOS" \
        -destination 'platform=iOS Simulator,name=iPhone 16' \
        -parallel-testing-enabled NO \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NOxcodebuild test \
